"""Compile per-bot references into a single decision file for cron inject.

Per ADR-002 (references RAG layer) and Phase J of plan
docs/plans/2026-05-07-multi-bot-references-restructure.md.

Selection rule (NOT a naive concat — anti-placeholder rule):
    1. Always include references/global-trading-config.md verbatim.
    2. For each bot-specific reference (references/<bot>/*.md):
       - the full ## Quick Decision Heuristics section, AND
       - the first paragraph (<=400 chars) of each ## topic section.
    3. For each shared reference (references/shared/*.md):
       - same rule as #2.
    4. Hard-fail (exit 1) if final tiktoken count > 8000.
       No silent truncation — operator must trim sources.

Usage:
    python infra/scripts/compile_refs.py --bot crypto
    python infra/scripts/compile_refs.py --bot polymarket
    python infra/scripts/compile_refs.py --bot crypto --refs-root /tmp/test  # for tests

Output:
    references/<bot>/compiled/refs-<bot>-decision.md  (or under --refs-root)

Exit codes:
    0  success
    1  token budget exceeded OR source files missing
"""
from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path
from typing import Iterable

import tiktoken


TOKEN_BUDGET = 8000
FIRST_PARA_MAX_CHARS = 400


def _autogen_header(bot: str) -> str:
    ts = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    return (
        f"<!-- AUTOGENERATED by infra/scripts/compile_refs.py for bot='{bot}' "
        f"at {ts}. DO NOT EDIT BY HAND. Regenerate via "
        f"`python infra/scripts/compile_refs.py --bot {bot}`. -->\n\n"
    )


def _select_from_topic_file(text: str, source_label: str) -> str:
    """Apply the Phase J selection rule to one ## -section reference file:
    - Take first paragraph (<=FIRST_PARA_MAX_CHARS chars) of each ## section
      EXCEPT 'Quick Decision Heuristics'.
    - Take the FULL 'Quick Decision Heuristics' section.

    Returns concatenated selection prefixed by the source label header.
    """
    lines = text.splitlines()
    sections: list[tuple[str, list[str]]] = []  # [(heading, body_lines)]
    cur_heading: str | None = None
    cur_body: list[str] = []
    for line in lines:
        if line.startswith("## "):
            if cur_heading is not None:
                sections.append((cur_heading, cur_body))
            cur_heading = line.strip()
            cur_body = []
        elif cur_heading is not None:
            cur_body.append(line)
    if cur_heading is not None:
        sections.append((cur_heading, cur_body))

    out: list[str] = [f"### Source: {source_label}", ""]
    for heading, body in sections:
        out.append(heading)
        if heading.lower().endswith("quick decision heuristics"):
            # Full section.
            out.extend(body)
        else:
            # First paragraph (until first blank line OR FIRST_PARA_MAX_CHARS reached).
            buf: list[str] = []
            char_count = 0
            for bline in body:
                if not bline.strip() and buf:
                    break  # blank line ends paragraph (after any content)
                if char_count + len(bline) > FIRST_PARA_MAX_CHARS:
                    remaining = FIRST_PARA_MAX_CHARS - char_count
                    if remaining > 10:  # only include if meaningfully long
                        buf.append(bline[:remaining] + "...")
                    break
                buf.append(bline)
                char_count += len(bline)
            out.extend(buf)
        out.append("")  # spacer between sections
    out.append("")
    return "\n".join(out)


def _build_compiled(refs_root: Path, bot: str) -> str:
    """Build the compiled refs body for the given bot."""
    body_parts: list[str] = []
    body_parts.append(_autogen_header(bot))
    body_parts.append(f"# Compiled Decision Reference — {bot}-bot\n")
    body_parts.append(
        "> Per ADR-002. Injected at every cron cycle via `--append-system-prompt-file`.\n"
        "> Sources: `references/global-trading-config.md` (verbatim) +\n"
        f"> `references/{bot}/*.md` (Quick Heuristics + first paragraph per topic) +\n"
        "> `references/shared/*.md` (same selection rule).\n\n"
    )

    # 1. Global config — verbatim
    global_cfg = refs_root / "global-trading-config.md"
    if not global_cfg.is_file():
        print(
            f"ERROR: required source missing: {global_cfg}",
            file=sys.stderr,
        )
        sys.exit(1)
    body_parts.append("## --- VERBATIM: global-trading-config.md ---\n\n")
    body_parts.append(global_cfg.read_text(encoding="utf-8"))
    body_parts.append("\n\n")

    # 2. Bot-specific
    bot_dir = refs_root / bot
    if not bot_dir.is_dir():
        print(f"ERROR: bot dir missing: {bot_dir}", file=sys.stderr)
        sys.exit(1)
    bot_md_files = sorted(p for p in bot_dir.glob("*.md") if p.is_file())
    if bot_md_files:
        body_parts.append(f"## --- SELECTED: references/{bot}/ ---\n\n")
        for f in bot_md_files:
            label = f"references/{bot}/{f.name}"
            body_parts.append(_select_from_topic_file(f.read_text(encoding="utf-8"), label))
            body_parts.append("\n")

    # 3. Shared
    shared_dir = refs_root / "shared"
    if shared_dir.is_dir():
        shared_md_files = sorted(p for p in shared_dir.glob("*.md") if p.is_file())
        if shared_md_files:
            body_parts.append("## --- SELECTED: references/shared/ ---\n\n")
            for f in shared_md_files:
                label = f"references/shared/{f.name}"
                body_parts.append(
                    _select_from_topic_file(f.read_text(encoding="utf-8"), label)
                )
                body_parts.append("\n")

    return "".join(body_parts)


def _count_tokens(text: str) -> int:
    enc = tiktoken.encoding_for_model("gpt-4")
    return len(enc.encode(text))


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bot", required=True, choices=["crypto", "polymarket"])
    parser.add_argument(
        "--refs-root",
        default=None,
        help="Override references/ root (for testing). Default: <repo>/references",
    )
    args = parser.parse_args(argv)

    repo_root = Path(__file__).resolve().parents[2]
    refs_root = Path(args.refs_root) if args.refs_root else (repo_root / "references")
    refs_root = refs_root.resolve()

    body = _build_compiled(refs_root, args.bot)
    token_count = _count_tokens(body)

    if token_count > TOKEN_BUDGET:
        print(
            f"ERROR: compiled refs for bot='{args.bot}' = {token_count} tokens, "
            f"exceeds budget {TOKEN_BUDGET}. Trim source references; do NOT auto-truncate.",
            file=sys.stderr,
        )
        return 1

    out_dir = refs_root / args.bot / "compiled"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"refs-{args.bot}-decision.md"
    out_path.write_text(body, encoding="utf-8")
    print(
        f"OK: wrote {out_path} ({token_count} tokens, {len(body):,} chars)",
        file=sys.stdout,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
